Fix intermittent exception due to duplicate ID
Fixes intermittent exception.

#    type: uncaughtError
#    file: regression.js:242
#    error: '/\/[^\/]*\/?$/' is not a function (evaluating 'casper.fill( 'form#image-diff', {

                'one': one,

                'two': two

        } )')
#           TypeError: '/\/[^\/]*\/?$/' is not a function (evaluating 'casper.fill( 'form#image-diff', {

#                       'one': one,

#                       'two': two

#               } )')
#               at asyncCompare (...npm/node_modules/phantomcss/phantomcss.js:242)
#               at ../npm/node_modules/phantomcss/phantomcss.js:417
#               at runStep (.../npm/node_modules/casperjs/modules/casper.js:1553)
#               at checkStep (.../npm/node_modules/casperjs/modules/casper.js:399)
#    stack: not provided